# Copyright (c) 2024 Sudiata Giddasira, Inc. d/b/a Quipu Research Labs, LLC d/b/a KR-Labs™
# SPDX-License-Identifier: MIT

# ReadTheDocs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

# Build settings
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_build:
      - pip install poetry || pip install --upgrade pip setuptools wheel
    post_checkout:
      - git fetch --unshallow || true

# Python configuration
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
    - requirements: docs/requirements.txt

# Sphinx configuration
sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false

# Format configuration
formats:
  - pdf
  - epub

# Search configuration
search:
  ranking:
    api/*: 2
    guide/*: 3
    reference/*: 1
