# ----------------------------------------------------------------------
# © 2025 KR-Labs. All rights reserved.
# KR-Labs™ is a trademark of Quipu Research Labs, LLC,
# a subsidiary of Sudiata Giddasira, Inc.
# ----------------------------------------------------------------------
# SPDX-License-Identifier: MIT

name: Markdown Quality

on:
  push:
    branches: [main]
    paths:
      - '**.md'
      - '.github/workflows/markdown-quality.yml'
  pull_request:
    branches: [main]
    paths:
      - '**.md'

jobs:
  markdown-lint:
    name: Lint Markdown Files
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli
      
      - name: Run markdownlint
        run: |
          markdownlint '**/*.md' \
            --ignore node_modules \
            --ignore htmlcov \
            --config .markdownlint.json || true
        continue-on-error: true
  
  link-checker:
    name: Check Markdown Links
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install markdown-link-check
        run: npm install -g markdown-link-check
      
      - name: Check links in README
        run: |
          markdown-link-check README.md \
            --config .markdown-link-check.json || true
        continue-on-error: true
      
      - name: Check links in documentation
        run: |
          find docs -name '*.md' -exec markdown-link-check {} \
            --config .markdown-link-check.json \; || true
        continue-on-error: true
  
  spelling-check:
    name: Spell Check Documentation
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install cspell
        run: npm install -g cspell
      
      - name: Run spell checker
        run: |
          cspell "**/*.md" \
            --config .cspell.json \
            --no-progress || true
        continue-on-error: true
